create extension if not exists vector;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_documents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  original_name text not null,
  storage_path text not null unique,
  status text not null default 'uploaded' check (status in ('uploaded', 'processing', 'ready', 'error')),
  error_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.document_chunks (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.user_documents(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(768) not null,
  created_at timestamptz not null default now()
);

create index if not exists document_chunks_document_id_idx on public.document_chunks(document_id);
create index if not exists document_chunks_user_id_idx on public.document_chunks(user_id);
create index if not exists document_chunks_embedding_idx on public.document_chunks using hnsw (embedding vector_cosine_ops);

create table if not exists public.summaries (
  document_id uuid primary key references public.user_documents(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_sessions (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  document_id uuid not null references public.user_documents(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (id, user_id, document_id)
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  session_id text not null references public.chat_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_session_created_idx on public.chat_messages(session_id, created_at desc);

create table if not exists public.processing_errors (
  id bigint generated by default as identity primary key,
  document_id uuid references public.user_documents(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  error text not null,
  created_at timestamptz not null default now()
);

create or replace function public.match_document_chunks(
  query_embedding vector(768),
  requested_document_id uuid,
  match_threshold float default 0.45,
  match_count int default 8
)
returns table (content text, metadata jsonb, similarity float)
language sql stable security invoker
set search_path = public
as $$
  select
    chunks.content,
    chunks.metadata,
    1 - (chunks.embedding <=> query_embedding) as similarity
  from public.document_chunks as chunks
  where chunks.document_id = requested_document_id
    and chunks.user_id = (select auth.uid())
    and 1 - (chunks.embedding <=> query_embedding) > match_threshold
  order by chunks.embedding <=> query_embedding
  limit match_count;
$$;

alter table public.user_documents enable row level security;
alter table public.document_chunks enable row level security;
alter table public.summaries enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.processing_errors enable row level security;

alter table public.profiles enable row level security;

create policy "Users manage their profile" on public.profiles
  for all using (auth.uid() = id) with check (auth.uid() = id);

create policy "Users manage their documents" on public.user_documents
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users read their chunks" on public.document_chunks
  for select using (auth.uid() = user_id);
create policy "Users read their summaries" on public.summaries
  for select using (auth.uid() = user_id);
create policy "Users manage their sessions" on public.chat_sessions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage their messages" on public.chat_messages
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users read processing errors" on public.processing_errors
  for select using (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do nothing;

create policy "Users manage document files" on storage.objects
  for all using (bucket_id = 'documents' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'documents' and (storage.foldername(name))[1] = auth.uid()::text);
